#pragma config(Motor,  port1,           TR,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BL,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goForward(int x, int y){
	motor[TL] = x;
	motor[TR] = y;
	motor[BL] = x;
	motor[BR] = y;
}
void goBack(int x, int y){
	motor[TL] = -x;
	motor[TR] = -y;
	motor[BL] = -x;
	motor[BR] = -y;
}
void turnLeft(int x, int y){
	motor[TL] = -x;
	motor[TR] = y;
	motor[BL] = -x;
	motor[BR] = y;
}
void turnRight(int x, int y){
	motor[TL] = x;
	motor[TR] = -y;
	motor[BL] = x;
	motor[BR] = -y;
}

	task main(){
		if()
	goForward(127, 127)
}





}
