#pragma config(Motor,  port1,           TR,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BL,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Top motors are pointing outwards and the back motor are pointing inwards//
//

int JoystickPos1 = vexRT[Ch4];
int JoystickPos2 = vexRT[Ch1];

void DirChange () {
	motor[TR] = vexRT[Ch2];
	motor[BR] = vexRT[Ch2];
	motor[TL] = vexRT[Ch3];
	motor[BL] = vexRT[Ch3];
}

void StrafeLeft ()  {
	motor[TR] = JoystickPos2 *-1;
	motor[BR] = JoystickPos2;
	motor[TL] = JoystickPos1;
	motor[BL] = JoystickPos1 * -1;

}

void StrafeRight ()  {
	motor[TR] = JoystickPos2;
	motor[BR] = JoystickPos2 * -1;
	motor[TL] = JoystickPos1 * -1;
	motor[BL] = JoystickPos1;

}

task main()
{

motor[TR] = vexRT[Ch1];
motor[BR] = vexRT[Ch1];
motor[TL] = vexRT[Ch4];
motor[BL] = vexRT[Ch4];

DirChange ();

StrafeLeft ();

StrafeRight ();


}
